server:
  port: 8687
  servlet:
    context-path: /api

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
logging:
  level:
    org.springframework.web: DEBUG

